### ISSUE TITLE
Duplicate keyword

### ISSUE THREAD

**Issue by masonjmj** [cyphar/heisig-rtk-index#1]
In the INDEX_VOL1.csv from the released zip file and in the KANJI_INDEX.csv from the project, both kanji 96 町 and kanji 221 村 have the keyword town. In my physical copy of RTK-1 6th edition kanji 96 町 is town and kanji 221 村 is village.

**Comment by cyphar** [comment]
Ah, annoyingly I found and fixed this in fbecfda169096039c8c610a0076ac69c0bc651ce but I screwed up the fix. It's been fixed in  4c3edac4a313acd353b99a9eb62ce5044ccd483d now.

**Comment by cyphar** [comment]
The original issue was that the keywords were swapped, and I accidentally made them have the same keyword because the data-set it's based on has both 5th and 6th edition keywords and I only changed one of each for each entry.
